// ── BASE PRODUCTS ──
const BASE = [
  {cat:"濃",flag:"🇭🇰",name:"濃AOne紅12號",price:270},
  {cat:"濃",flag:"🇭🇰",name:"濃曼徹斯特12號",price:280},
  {cat:"濃",flag:"🇲🇴",name:"紅摩迪12MG",price:290},
  {cat:"濃",flag:"🇯🇵",name:"日本版原裝中純萬",price:415},
  {cat:"濃",flag:"🇯🇵",name:"日本版原裝紅萬",price:415},
  {cat:"濃",flag:"🇯🇵",name:"日本版7仔原裝紅萬",price:470},
  {cat:"純",flag:"🇭🇰",name:"純AOne藍8號",price:270},
  {cat:"純",flag:"🇭🇰",name:"極純奧沙銀HO 4mg",price:270},
  {cat:"純",flag:"🇰🇷",name:"純白迪8 mg",price:290},
  {cat:"純",flag:"🇲🇴",name:"藍摩迪4MG",price:290},
  {cat:"純",flag:"🇭🇰",name:"極純曼徹斯特2號",price:280},
  {cat:"純",flag:"🇭🇰",name:"純曼徹斯特8號",price:280},
  {cat:"純",flag:"🇯🇵",name:"日本版原裝白萬",price:415},
  {cat:"純",flag:"🇯🇵",name:"日本版7仔原裝白萬",price:470},
  {cat:"純",flag:"🇯🇵",name:"日本版原裝萬事發原味1/3/6/8/10號",price:410},
  {cat:"純",flag:"🇯🇵",name:"日本版7仔E系原裝萬事發原味1/6號",price:420},
  {cat:"純",flag:"🇯🇵",name:"日本版7仔原裝七星7號",price:460},
  {cat:"純",flag:"🇯🇵",name:"日本版7仔原裝黑魔鬼摩卡香草/朱古力",price:460},
  {cat:"純幼",flag:"🇰🇷",name:"韓國機場純藍ESSE",price:275},
  {cat:"薄荷粗",flag:"🇭🇰",name:"奧沙C4HO 6mg",price:290},
  {cat:"薄荷粗",flag:"🇭🇰",name:"奧沙C6HO 6mg",price:290},
  {cat:"薄荷粗",flag:"🇭🇰",name:"奧沙雙珠藍莓HO 8mg",price:295},
  {cat:"薄荷粗",flag:"🇭🇰",name:"奧沙雙珠蜜瓜HO 8mg",price:295},
  {cat:"薄荷粗",flag:"🇰🇷",name:"雙珠冰極迪寶路 2mg",price:305},
  {cat:"薄荷粗",flag:"🇰🇷",name:"雙珠蜜瓜迪寶路 5mg",price:305},
  {cat:"薄荷粗",flag:"🇰🇷",name:"雙珠蜜瓜迪寶路 8mg",price:305},
  {cat:"薄荷粗",flag:"🇰🇷",name:"雙珠藍莓迪寶路 5mg",price:305},
  {cat:"薄荷粗",flag:"🇰🇷",name:"雙珠藍莓迪寶路 8mg",price:305},
  {cat:"薄荷粗",flag:"🇲🇴",name:"雙珠冰川摩迪5MG",price:305},
  {cat:"薄荷粗",flag:"🇲🇴",name:"雙珠蜜瓜摩迪5MG",price:305},
  {cat:"薄荷粗",flag:"🇲🇴",name:"雙珠藍莓摩迪5MG",price:305},
  {cat:"薄荷粗",flag:"🇲🇴",name:"雙珠藍莓摩迪8MG",price:305},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝黑冰5/8號",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝純薄荷萬4/8號",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝黑萬",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝雙珠草莓萬",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝熱情果萬",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝檸檬dry萬",price:415},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝雙珠薄荷萬",price:470},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝純薄荷萬4/8號",price:470},
  {cat:"薄荷粗",flag:"🇭🇰",name:"香港機場萬事發赤玉1",price:490},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝萬事發赤玉5/8號",price:410},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝萬事發藍莓5/8號",price:410},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版原裝萬事發藍莓8號",price:410},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝萬事發藍莓1/5/8號",price:460},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝萬事發檸檬1號",price:460},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝BJ青檸8/芒果5",price:420},
  {cat:"薄荷粗",flag:"🇯🇵",name:"日本版7仔原裝BJ隨機5",price:460},
  {cat:"薄荷幼",flag:"🇰🇷",name:"幼雙珠士多啤梨寒冰",price:335},
  {cat:"薄荷幼",flag:"🇰🇷",name:"韓國機場雙珠橙ESSE",price:285},
  {cat:"薄荷幼",flag:"🇰🇷",name:"韓國機場雙珠提子ESSE",price:285},
  {cat:"薄荷幼",flag:"🇰🇷",name:"黑冰迪寶路1號(幼)",price:290},
  {cat:"薄荷幼",flag:"🇰🇷",name:"黑冰迪寶路5號(幼)",price:290},
  {cat:"薄荷幼",flag:"🇰🇷",name:"冰極迪寶路1號(幼)",price:290},
  {cat:"薄荷幼",flag:"🇰🇷",name:"雙珠蜜瓜迪寶路5號(幼)",price:305},
  {cat:"薄荷幼",flag:"🇰🇷",name:"雙珠藍莓迪寶路1號(幼)",price:305},
  {cat:"薄荷幼",flag:"🇰🇷",name:"雙珠藍莓迪寶路5號(幼)",price:305},
  {cat:"薄荷幼",flag:"🇰🇷",name:"雙珠紅酒迪寶路1號(幼)",price:305},
  {cat:"薄荷幼",flag:"🇰🇷",name:"雙珠紅酒迪寶路5號(幼)",price:305},
  {cat:"薄荷幼",flag:"🇰🇷",name:"(幼)MAC薄荷爆珠",price:245},
  {cat:"薄荷幼",flag:"🇭🇰",name:"幼香港機場健牌赤冰薄1",price:490},
  {cat:"薄荷幼",flag:"🇯🇵",name:"幼日本版原裝健牌冰薄1/金薄1",price:410},
  {cat:"薄荷幼",flag:"🇯🇵",name:"幼日本版7仔原裝健牌冰薄5/紫薄1/金薄1",price:420},
  {cat:"薄荷幼",flag:"🇯🇵",name:"幼日本版原裝E系藍莓1",price:420},
  {cat:"中關",flag:"🇨🇳",name:"中南海藍裝8號",price:230},
  {cat:"中關",flag:"🇨🇳",name:"中南海金裝8號",price:240},
  {cat:"中關",flag:"🇨🇳",name:"硬南洋",price:230},
  {cat:"中關",flag:"🇨🇳",name:"軟南洋",price:220},
  {cat:"中關",flag:"🇨🇳",name:"硬經典",price:250},
  {cat:"中關",flag:"🇨🇳",name:"軟經典",price:250},
  {cat:"中關",flag:"🇨🇳",name:"硬廣喜",price:255},
  {cat:"中關",flag:"🇨🇳",name:"1906經典",price:245},
  {cat:"中關",flag:"🇨🇳",name:"百年龍鳳",price:260},
  {cat:"中關",flag:"🇨🇳",name:"金芙蓉(湖南版)",price:255},
  {cat:"中關",flag:"🇨🇳",name:"粗荷花",price:275},
  {cat:"中關",flag:"🇨🇳",name:"軟黃鶴樓",price:250},
  {cat:"中關",flag:"🇨🇳",name:"軟紅牡丹",price:250},
  {cat:"中關",flag:"🇨🇳",name:"白紅塔山",price:250},
  {cat:"中關",flag:"🇨🇳",name:"硬中華",price:280},
  {cat:"中關",flag:"🇨🇳",name:"軟中華",price:285},
  {cat:"中關",flag:"🇨🇳",name:"幼南京藍(炫赫門)",price:240},
  {cat:"中關",flag:"🇨🇳",name:"幼南京金(十二金釵)",price:240},
  {cat:"中關",flag:"🇨🇳",name:"幼南京黃(雨花石)",price:240},
  {cat:"中關",flag:"🇨🇳",name:"陳皮貴煙",price:240},
];
